---
- hosts: localhost

  connection: local

  tasks:
    # - name: Create resource group
    #   azure_rm_resourcegroup:
    #     name: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
    #     location: westeurope
    #   register: rg_result
    # - debug:
    #     var: rg_result

    # - name: Create virtual network
    #   azure_rm_virtualnetwork:
    #     resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
    #     name: VNET-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
    #     address_prefixes: "10.0.0.0/16"
    #   register: vnet_result
    # - debug:
    #     var: vnet_result

    # - name: Add subnet
    #   azure_rm_subnet:
    #     resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
    #     name: cluster
    #     address_prefix: "10.0.1.0/24"
    #     virtual_network: VNET-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
    #   register: subnet_result
    # - debug:
    #     var: subnet_result

    - include_tasks: tasks/ip-address.yml

    - name: LoadBalancer
      azure_rm_loadbalancer:
        name: Ansible-{{ lookup('env', 'ENVIRONMENT') }}-LoadBalancer
        resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
        location: westeurope
        frontend_ip_configurations: 
          - name: LoadBalancerFrontEnd
            public_ip_address: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-LoadBalancer
        backend_address_pools:
          - name: PoolPrincipal
        probes:
          - name: apik-server-tcp-integrity-probe
            port: 80
            protocol: Tcp
        load_balancing_rules:
          - name: HTTP
            frontend_ip_configuration: LoadBalancerFrontEnd
            backend_address_pool: PoolPrincipal
            frontend_port: 80
            backend_port: 80
            probe: apik-server-tcp-integrity-probe
          - name: HTTPS
            frontend_ip_configuration: LoadBalancerFrontEnd
            backend_address_pool: PoolPrincipal
            frontend_port: 443
            backend_port: 443
            probe: apik-server-tcp-integrity-probe

    # - include_tasks: tasks/security-group.yml

    - include_tasks: tasks/net-interface.yml

#    # - include_tasks: tasks/disks.yml

    # - include_tasks: tasks/create-vm.yml



