---
  - name: Update / Upgrade
    shell: |
      sudo apt update
      sudo apt upgrade -y
    register: result

  - debug:
      msg: "{{result.stdout_lines}}"


  - name: "Installation of docker daemon (This step can take a certain time, don't stop the execution of the playbook : ~5 mins for 3 hosts)"
    shell: |
      sudo apt-get install -y ca-certificates curl gnupg lsb-release
      sudo mkdir -p /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    register: result

  - debug:
      msg: "{{result.stdout_lines}}"


  - name: Verification of Docker
    shell: |
      sudo docker run hello-world
    register: result

  - debug:
      msg: "{{result.stdout_lines}}"

