---
  # Création des adresses IP pour les trois machines du cluster.
  - name: Create public IP address for Ansible-{{ lookup('env', 'ENVIRONMENT') }}-1
    azure_rm_publicipaddress:
      resource_group: Resource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      allocation_method: Static
      sku: standard
      zones: 1
      name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-1
    register: output_ip_address_1

  - debug:
      var: output_ip_address_1["state"]["ip_address"]

  - name: Create public IP address for Ansible-{{ lookup('env', 'ENVIRONMENT') }}-2
    azure_rm_publicipaddress:
      resource_group: Resource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      allocation_method: Static
      sku: standard
      zones: 2
      name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-2
    register: output_ip_address_2

  - debug:
      var: output_ip_address_2["state"]["ip_address"]

  - name: Create public IP address for Ansible-{{ lookup('env', 'ENVIRONMENT') }}-3
    azure_rm_publicipaddress:
      resource_group: Resource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      allocation_method: Static
      sku: standard
      zones: 3
      name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-3
    register: output_ip_address_3

  - debug:
      var: output_ip_address_3["state"]["ip_address"]



  - name: Create public IP address for LoadBalancer
    azure_rm_publicipaddress:
      resource_group: Resource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      allocation_method: Static
      sku: standard
      zones: ['1']
      name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-LoadBalancer
    register: output_ip_address

  - debug:
      var: output_ip_address["state"]["ip_address"]
