---
  - name: Create a network interface
    azure_rm_networkinterface:
      name: Network-Interface-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-1
      resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      virtual_network: VNET-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      subnet_name: cluster
      security_group: Security-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-1
      ip_configurations:
          - name: default
            public_ip_address_name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-1
            primary: True

  - name: Create a network interface
    azure_rm_networkinterface:
      name: Network-Interface-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-2
      resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      virtual_network: VNET-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      subnet_name: cluster
      security_group: Security-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-2
      ip_configurations:
          - name: default
            public_ip_address_name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-2
            primary: True

  - name: Create a network interface
    azure_rm_networkinterface:
      name: Network-Interface-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-3
      resource_group: Ressource-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      virtual_network: VNET-Ansible-{{ lookup('env', 'ENVIRONMENT') }}
      subnet_name: cluster
      security_group: Security-Group-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-3
      ip_configurations:
          - name: default
            public_ip_address_name: IP-Ansible-{{ lookup('env', 'ENVIRONMENT') }}-3
            primary: True
